<?php

use App\Models\CustomerCompany;
use App\Models\OrganizationElement;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Cache;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Pagination\Paginator;



function customPagination($total, int $per_page, int $current_page = null) {
    $current_page = $current_page ? : Paginator::resolveCurrentPage() ? : 1;
    $per_page = $per_page ? : request('per_page') ? : 10;



    $from = (($current_page - 1) * $per_page);
    if($total < $per_page){
        $from = 1;
    }else {
        $from = $from +1;
    }

    $to = ($from -1) + $per_page;

    if($total < $per_page){
        $to = $total;
    }

    if($total < ($per_page * $current_page)){
        $from = null;
        $to = null;
    }


    $last_page = ceil($total / $per_page);

    return [
        'total'             =>  $total,
        'per_page'          =>  $per_page,
        'current_page'      =>  $current_page,
        'last_page'         =>  $last_page,
        // 'next_page_url'     =>  $results->nextPageUrl(),
        // 'prev_page_url'     =>  $results->previousPageUrl(),
        'from'              =>  $from ,
        'to'                =>  $to,
    ];
}
/**
 * Get Next Auto-increment id
 *
 * @param string $table
 * @return string
 */
function nextIncrementId(string $table): string
{
    // $statement = DB::select("show table status like '{$table}'");
    // return $statement[0]->Auto_increment;

    //Temporary solutions
    return DB::table($table)->max('id') + 1;
}





/**
 * Get Next Auto-increment id with prefix
 *
 * @param string $table
 * @param string $prefix
 * @return string
 */
function nextId(string $table, string $prefix = ''): string
{
    return $prefix . sprintf("%05d", nextIncrementId($table));
}


/**
 * Get Country Code by country abbreviation
 *
 * @param String $abbribiation
 * @return void
 */
function getCountryCodeByAbbreviation($abbribiation)
{
    $countries =  Cache::rememberForever('countries', function () {
        $countries = file_get_contents(resource_path('js/countries.json'));
        return json_decode($countries, true);
    });

    $dialCode = null;

    foreach ($countries as $country) {
        if (isset($country['dialCode']) && (strtolower($abbribiation) === strtolower($country['iso']))) {
            $dialCode = $country['dialCode'];
            break;
        }
    }
    return $dialCode;
}



/**
 * Get Translated Country name
 * @param string $code Contry ISO2 code
 * @param string $local Country local support en de fr
 *
 * @return string|null
 */
function getCountryNameFromCode($code, $local = 'en')
{

    $countries = [
        "en" => [
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "DZ" => "Algeria",
            "AS" => "American Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarctica",
            "AG" => "Antigua and Barbuda",
            "AR" => "Argentina",
            "AM" => "Armenia",
            "AW" => "Aruba",
            "AU" => "Australia",
            "AT" => "Austria",
            "AZ" => "Azerbaijan",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesh",
            "BB" => "Barbados",
            "BY" => "Belarus",
            "BE" => "Belgium",
            "BZ" => "Belize",
            "BJ" => "Benin",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivia",
            "BA" => "Bosnia and Herzegovina",
            "BW" => "Botswana",
            "BV" => "Bouvet Island",
            "BR" => "Brazil",
            "IO" => "British Indian Ocean Territory",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgaria",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Cambodia",
            "CM" => "Cameroon",
            "CA" => "Canada",
            "CV" => "Cape Verde",
            "KY" => "Cayman Islands",
            "CF" => "Central African Republic",
            "TD" => "Chad",
            "CL" => "Chile",
            "CN" => "China",
            "CX" => "Christmas Island",
            "CC" => "Cocos (Keeling) Islands",
            "CO" => "Colombia",
            "KM" => "Comoros",
            "CG" => "Congo",
            "CD" => "Congo",
            "CK" => "Cook Islands",
            "CR" => "Costa Rica",
            "CI" => "Ivory Coast",
            "HR" => "Croatia",
            "CU" => "Cuba",
            "CY" => "Cyprus",
            "CZ" => "Czechia",
            "DK" => "Denmark",
            "DJ" => "Djibouti",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "EC" => "Ecuador",
            "EG" => "Egypt",
            "SV" => "El Salvador",
            "GQ" => "Equatorial Guinea",
            "ER" => "Eritrea",
            "EE" => "Estonia",
            "ET" => "Ethiopia",
            "FK" => "Falkland Islands (Malvinas)",
            "FO" => "Faroe Islands",
            "FJ" => "Fiji",
            "FI" => "Finland",
            "FR" => "France",
            "GF" => "French Guiana",
            "PF" => "French Polynesia",
            "TF" => "French Southern Territories",
            "GA" => "Gabon",
            "GM" => "Gambia",
            "GE" => "Georgia",
            "DE" => "Germany",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Greece",
            "GL" => "Greenland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinea",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard Island and McDonald Islands",
            "VA" => "Holy See (Vatican City State)",
            "HN" => "Honduras",
            "HK" => "Hong Kong",
            "HU" => "Hungary",
            "IS" => "Iceland",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IL" => "Israel",
            "IT" => "Italy",
            "JM" => "Jamaica",
            "JP" => "Japan",
            "JO" => "Jordan",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KI" => "Kiribati",
            "KP" => "North Korea",
            "KR" => "South Korea",
            "KW" => "Kuwait",
            "KG" => "Kyrgyzstan",
            "LA" => "Lao People's Democratic Republic",
            "LV" => "Latvia",
            "LB" => "Lebanon",
            "LS" => "Lesotho",
            "LR" => "Liberia",
            "LY" => "Libya",
            "LI" => "Liechtenstein",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "MO" => "Macao",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malta",
            "MH" => "Marshall Islands",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MU" => "Mauritius",
            "YT" => "Mayotte",
            "MX" => "Mexico",
            "FM" => "Micronesia, Federated States of",
            "MD" => "Moldova, Republic of",
            "MC" => "Monaco",
            "MN" => "Mongolia",
            "MS" => "Montserrat",
            "MA" => "Morocco",
            "MZ" => "Mozambique",
            "MM" => "Myanmar",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "NC" => "New Caledonia",
            "NZ" => "New Zealand",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolk Island",
            "MK" => "North Macedonia",
            "MP" => "Northern Mariana Islands",
            "NO" => "Norway",
            "OM" => "Oman",
            "PK" => "Pakistan",
            "PW" => "Palau",
            "PS" => "Palestine",
            "PA" => "Panama",
            "PG" => "Papua New Guinea",
            "PY" => "Paraguay",
            "PE" => "Peru",
            "PH" => "Philippines",
            "PN" => "Pitcairn",
            "PL" => "Poland",
            "PT" => "Portugal",
            "PR" => "Puerto Rico",
            "QA" => "Qatar",
            "RE" => "Reunion",
            "RO" => "Romania",
            "RU" => "Russia",
            "RW" => "Rwanda",
            "SH" => "Saint Helena",
            "KN" => "Saint Kitts and Nevis",
            "LC" => "Saint Lucia",
            "PM" => "Saint Pierre and Miquelon",
            "VC" => "Saint Vincent and the Grenadines",
            "WS" => "Samoa",
            "SM" => "San Marino",
            "ST" => "Sao Tome and Principe",
            "SA" => "Saudi Arabia",
            "SN" => "Senegal",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapore",
            "SK" => "Slovakia",
            "SI" => "Slovenia",
            "SB" => "Solomon Islands",
            "SO" => "Somalia",
            "ZA" => "South Africa",
            "GS" => "South Georgia and the South Sandwich Islands",
            "ES" => "Spain",
            "LK" => "Sri Lanka",
            "SD" => "Sudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard and Jan Mayen",
            "SZ" => "Eswatini",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syrian Arab Republic",
            "TW" => "Taiwan, Province of China",
            "TJ" => "Tajikistan",
            "TZ" => "Tanzania",
            "TH" => "Thailand",
            "TL" => "Timor-Leste",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad and Tobago",
            "TN" => "Tunisia",
            "TR" => "Turkey",
            "TM" => "Turkmenistan",
            "TC" => "Turks and Caicos Islands",
            "TV" => "Tuvalu",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "AE" => "United Arab Emirates",
            "GB" => "United Kingdom",
            "US" => "United States of America",
            "UM" => "United States Minor Outlying Islands",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VU" => "Vanuatu",
            "VE" => "Venezuela",
            "VN" => "Vietnam",
            "VG" => "Virgin Islands, British",
            "VI" => "Virgin Islands, U.S.",
            "WF" => "Wallis and Futuna",
            "EH" => "Western Sahara",
            "YE" => "Yemen",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe",
            "AX" => "Åland Islands",
            "BQ" => "Bonaire, Sint Eustatius and Saba",
            "CW" => "Curaçao",
            "GG" => "Guernsey",
            "IM" => "Isle of Man",
            "JE" => "Jersey",
            "ME" => "Montenegro",
            "BL" => "Saint Barthélemy",
            "MF" => "Saint Martin (French part)",
            "RS" => "Serbia",
            "SX" => "Sint Maarten (Dutch part)",
            "SS" => "South Sudan",
            "XK" => "Kosovo"
        ],
        "de" => [
            "AF" => "Afghanistan",
            "AL" => "Albanien",
            "DZ" => "Algerien",
            "AS" => "Amerikanisch-Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarktis",
            "AG" => "Antigua und Barbuda",
            "AR" => "Argentinien",
            "AM" => "Armenien",
            "AW" => "Aruba",
            "AU" => "Australien",
            "AT" => "Österreich",
            "AZ" => "Aserbaidschan",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesch",
            "BB" => "Barbados",
            "BY" => "Belarus",
            "BE" => "Belgien",
            "BZ" => "Belize",
            "BJ" => "Benin",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivien",
            "BA" => "Bosnien und Herzegowina",
            "BW" => "Botswana",
            "BV" => "Bouvetinsel",
            "BR" => "Brasilien",
            "IO" => "Britisches Territorium im Indischen Ozean",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgarien",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Kambodscha",
            "CM" => "Kamerun",
            "CA" => "Kanada",
            "CV" => "Kap Verde",
            "KY" => "Kaimaninseln",
            "CF" => "Zentralafrikanische Republik",
            "TD" => "Tschad",
            "CL" => "Chile",
            "CN" => "China",
            "CX" => "Weihnachtsinsel",
            "CC" => "Kokosinseln",
            "CO" => "Kolumbien",
            "KM" => "Komoren",
            "CG" => "Republik Kongo",
            "CD" => "Kongo",
            "CK" => "Cookinseln",
            "CR" => "Costa Rica",
            "CI" => "Elfenbeinküste",
            "HR" => "Kroatien",
            "CU" => "Kuba",
            "CY" => "Zypern",
            "CZ" => "Tschechische Republik",
            "DK" => "Dänemark",
            "DJ" => "Dschibuti",
            "DM" => "Dominica",
            "DO" => "Dominikanische Republik",
            "EC" => "Ecuador",
            "EG" => "Ägypten",
            "SV" => "El Salvador",
            "GQ" => "Äquatorialguinea",
            "ER" => "Eritrea",
            "EE" => "Estland",
            "ET" => "Äthiopien",
            "FK" => "Falklandinseln",
            "FO" => "Färöer",
            "FJ" => "Fidschi",
            "FI" => "Finnland",
            "FR" => "Frankreich",
            "GF" => "Französisch-Guayana",
            "PF" => "Französisch-Polynesien",
            "TF" => "Französische Süd- und Antarktisgebiete",
            "GA" => "Gabun",
            "GM" => "Gambia",
            "GE" => "Georgien",
            "DE" => "Deutschland",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Griechenland",
            "GL" => "Grönland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinea",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard und McDonaldinseln",
            "VA" => "Vatikanstadt",
            "HN" => "Honduras",
            "HK" => "Hongkong",
            "HU" => "Ungarn",
            "IS" => "Island",
            "IN" => "Indien",
            "ID" => "Indonesien",
            "IR" => "Iran",
            "IQ" => "Irak",
            "IE" => "Irland",
            "IL" => "Israel",
            "IT" => "Italien",
            "JM" => "Jamaika",
            "JP" => "Japan",
            "JO" => "Jordanien",
            "KZ" => "Kasachstan",
            "KE" => "Kenia",
            "KI" => "Kiribati",
            "KP" => "Nordkorea",
            "KR" => "Südkorea",
            "KW" => "Kuwait",
            "KG" => "Kirgisistan",
            "LA" => "Laos",
            "LV" => "Lettland",
            "LB" => "Libanon",
            "LS" => "Lesotho",
            "LR" => "Liberia",
            "LY" => "Libyen",
            "LI" => "Liechtenstein",
            "LT" => "Litauen",
            "LU" => "Luxemburg",
            "MO" => "Macao",
            "MG" => "Madagaskar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Malediven",
            "ML" => "Mali",
            "MT" => "Malta",
            "MH" => "Marshallinseln",
            "MQ" => "Martinique",
            "MR" => "Mauretanien",
            "MU" => "Mauritius",
            "YT" => "Mayotte",
            "MX" => "Mexiko",
            "FM" => "Mikronesien",
            "MD" => "Moldawien",
            "MC" => "Monaco",
            "MN" => "Mongolei",
            "MS" => "Montserrat",
            "MA" => "Marokko",
            "MZ" => "Mosambik",
            "MM" => "Myanmar",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Niederlande",
            "NC" => "Neukaledonien",
            "NZ" => "Neuseeland",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolkinsel",
            "MK" => "Nordmazedonien",
            "MP" => "Nördliche Marianen",
            "NO" => "Norwegen",
            "OM" => "Oman",
            "PK" => "Pakistan",
            "PW" => "Palau",
            "PS" => "Staat Palästina",
            "PA" => "Panama",
            "PG" => "Papua-Neuguinea",
            "PY" => "Paraguay",
            "PE" => "Peru",
            "PH" => "Philippinen",
            "PN" => "Pitcairninseln",
            "PL" => "Polen",
            "PT" => "Portugal",
            "PR" => "Puerto Rico",
            "QA" => "Katar",
            "RE" => "Réunion",
            "RO" => "Rumänien",
            "RU" => "Russische Föderation",
            "RW" => "Ruanda",
            "SH" => "St. Helena",
            "KN" => "St. Kitts und Nevis",
            "LC" => "St. Lucia",
            "PM" => "Saint-Pierre und Miquelon",
            "VC" => "St. Vincent und die Grenadinen",
            "WS" => "Samoa",
            "SM" => "San Marino",
            "ST" => "São Tomé und Príncipe",
            "SA" => "Saudi-Arabien",
            "SN" => "Senegal",
            "SC" => "Seychellen",
            "SL" => "Sierra Leone",
            "SG" => "Singapur",
            "SK" => "Slowakei",
            "SI" => "Slowenien",
            "SB" => "Salomonen",
            "SO" => "Somalia",
            "ZA" => "Südafrika",
            "GS" => "Südgeorgien und die Südlichen Sandwichinseln",
            "ES" => "Spanien",
            "LK" => "Sri Lanka",
            "SD" => "Sudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard und Jan Mayen",
            "SZ" => "Eswatini",
            "SE" => "Schweden",
            "CH" => "Schweiz",
            "SY" => "Syrien, Arabische Republik",
            "TW" => "Taiwan",
            "TJ" => "Tadschikistan",
            "TZ" => "Tansania, Vereinigte Republik",
            "TH" => "Thailand",
            "TL" => "Osttimor",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad und Tobago",
            "TN" => "Tunesien",
            "TR" => "Türkei",
            "TM" => "Turkmenistan",
            "TC" => "Turks- und Caicosinseln",
            "TV" => "Tuvalu",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "AE" => "Vereinigte Arabische Emirate",
            "GB" => "Großbritannien",
            "US" => "Vereinigte Staaten von Amerika",
            "UM" => "United States Minor Outlying Islands",
            "UY" => "Uruguay",
            "UZ" => "Usbekistan",
            "VU" => "Vanuatu",
            "VE" => "Venezuela",
            "VN" => "Vietnam",
            "VG" => "Britische Jungferninseln",
            "VI" => "Amerikanische Jungferninseln",
            "WF" => "Wallis und Futuna",
            "EH" => "Westsahara",
            "YE" => "Jemen",
            "ZM" => "Sambia",
            "ZW" => "Simbabwe",
            "AX" => "Åland",
            "BQ" => "Bonaire",
            "CW" => "Curaçao",
            "GG" => "Guernsey",
            "IM" => "Insel Man",
            "JE" => "Jersey",
            "ME" => "Montenegro",
            "BL" => "Saint-Barthélemy",
            "MF" => "Saint-Martin",
            "RS" => "Serbien",
            "SX" => "Sint Maarten",
            "SS" => "Südsudan",
            "XK" => "Kosovo"
        ],
        "fr" => [
            "AF" => "Afghanistan",
            "AL" => "Albanie",
            "DZ" => "Algérie",
            "AS" => "Samoa américaines",
            "AD" => "Andorre",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarctique",
            "AG" => "Antigua-et-Barbuda",
            "AR" => "Argentine",
            "AM" => "Arménie",
            "AW" => "Aruba",
            "AU" => "Australie",
            "AT" => "Autriche",
            "AZ" => "Azerbaïdjan",
            "BS" => "Bahamas",
            "BH" => "Bahreïn",
            "BD" => "Bangladesh",
            "BB" => "Barbade",
            "BY" => "Biélorussie",
            "BE" => "Belgique",
            "BZ" => "Belize",
            "BJ" => "Bénin",
            "BM" => "Bermudes",
            "BT" => "Bhoutan",
            "BO" => "Bolivie",
            "BA" => "Bosnie-Herzégovine",
            "BW" => "Botswana",
            "BV" => "Île Bouvet",
            "BR" => "Brésil",
            "IO" => "Océan Indien Britannique",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgarie",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Cambodge",
            "CM" => "Cameroun",
            "CA" => "Canada",
            "CV" => "Cap-Vert",
            "KY" => "Îles Caïmans",
            "CF" => "République Centrafricaine",
            "TD" => "Tchad",
            "CL" => "Chili",
            "CN" => "Chine",
            "CX" => "Île Christmas",
            "CC" => "Îles Cocos",
            "CO" => "Colombie",
            "KM" => "Comores",
            "CG" => "République du Congo",
            "CD" => "République démocratique du Congo",
            "CK" => "Îles Cook",
            "CR" => "Costa Rica",
            "CI" => "Côte-d'Ivoire",
            "HR" => "Croatie",
            "CU" => "Cuba",
            "CY" => "Chypre",
            "CZ" => "République Tchèque",
            "DK" => "Danemark",
            "DJ" => "Djibouti",
            "DM" => "Dominique",
            "DO" => "République Dominicaine",
            "EC" => "Équateur",
            "EG" => "Égypte",
            "SV" => "El Salvador",
            "GQ" => "Guinée équatoriale",
            "ER" => "Érythrée",
            "EE" => "Estonie",
            "ET" => "Éthiopie",
            "FK" => "Îles Malouines",
            "FO" => "Îles Féroé",
            "FJ" => "Fidji",
            "FI" => "Finlande",
            "FR" => "France",
            "GF" => "Guyane française",
            "PF" => "Polynésie française",
            "TF" => "Terres australes françaises",
            "GA" => "Gabon",
            "GM" => "Gambie",
            "GE" => "Géorgie",
            "DE" => "Allemagne",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Grèce",
            "GL" => "Groenland",
            "GD" => "Grenade",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinée",
            "GW" => "Guinée-Bissau",
            "GY" => "Guyana",
            "HT" => "Haïti",
            "HM" => "Îles Heard-et-MacDonald",
            "VA" => "Saint-Siège (Vatican)",
            "HN" => "Honduras",
            "HK" => "Hong Kong",
            "HU" => "Hongrie",
            "IS" => "Islande",
            "IN" => "Inde",
            "ID" => "Indonésie",
            "IR" => "Iran",
            "IQ" => "Irak",
            "IE" => "Irlande",
            "IL" => "Israël",
            "IT" => "Italie",
            "JM" => "Jamaïque",
            "JP" => "Japon",
            "JO" => "Jordanie",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KI" => "Kiribati",
            "KP" => "Corée du Nord",
            "KR" => "Corée du Sud",
            "KW" => "Koweït",
            "KG" => "Kirghizistan",
            "LA" => "Laos",
            "LV" => "Lettonie",
            "LB" => "Liban",
            "LS" => "Lesotho",
            "LR" => "Libéria",
            "LY" => "Libye",
            "LI" => "Liechtenstein",
            "LT" => "Lituanie",
            "LU" => "Luxembourg",
            "MO" => "Macao",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaisie",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malte",
            "MH" => "Îles Marshall",
            "MQ" => "Martinique",
            "MR" => "Mauritanie",
            "MU" => "Maurice",
            "YT" => "Mayotte",
            "MX" => "Mexique",
            "FM" => "Micronésie",
            "MD" => "Moldavie",
            "MC" => "Monaco",
            "MN" => "Mongolie",
            "MS" => "Montserrat",
            "MA" => "Maroc",
            "MZ" => "Mozambique",
            "MM" => "Myanmar",
            "NA" => "Namibie",
            "NR" => "Nauru",
            "NP" => "Népal",
            "NL" => "Pays-Bas",
            "NC" => "Nouvelle-Calédonie",
            "NZ" => "Nouvelle-Zélande",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigéria",
            "NU" => "Niué",
            "NF" => "Île Norfolk",
            "MK" => "Macédoine du Nord",
            "MP" => "Îles Mariannes du Nord",
            "NO" => "Norvège",
            "OM" => "Oman",
            "PK" => "Pakistan",
            "PW" => "Palaos",
            "PS" => "Palestine",
            "PA" => "Panama",
            "PG" => "Papouasie-Nouvelle-Guinée",
            "PY" => "Paraguay",
            "PE" => "Pérou",
            "PH" => "Philippines",
            "PN" => "Îles Pitcairn",
            "PL" => "Pologne",
            "PT" => "Portugal",
            "PR" => "Porto Rico",
            "QA" => "Qatar",
            "RE" => "Réunion",
            "RO" => "Roumanie",
            "RU" => "Russie",
            "RW" => "Rwanda",
            "SH" => "Sainte-Hélène",
            "KN" => "Saint-Christophe-et-Niévès",
            "LC" => "Sainte-Lucie",
            "PM" => "Saint-Pierre-et-Miquelon",
            "VC" => "Saint-Vincent-et-les-Grenadines",
            "WS" => "Samoa",
            "SM" => "Saint-Marin",
            "ST" => "São Tomé-et-Principe",
            "SA" => "Arabie Saoudite",
            "SN" => "Sénégal",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapour",
            "SK" => "Slovaquie",
            "SI" => "Slovénie",
            "SB" => "Îles Salomon",
            "SO" => "Somalie",
            "ZA" => "Afrique du Sud",
            "GS" => "Géorgie du Sud-et-les Îles Sandwich du Sud",
            "ES" => "Espagne",
            "LK" => "Sri Lanka",
            "SD" => "Soudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard et Île Jan Mayen",
            "SZ" => "Royaume d'Eswatini",
            "SE" => "Suède",
            "CH" => "Suisse",
            "SY" => "Syrie",
            "TW" => "Taïwan",
            "TJ" => "Tadjikistan",
            "TZ" => "République unie de Tanzanie",
            "TH" => "Thaïlande",
            "TL" => "Timor-Leste",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinité-et-Tobago",
            "TN" => "Tunisie",
            "TR" => "Turquie",
            "TM" => "Turkménistan",
            "TC" => "Îles Turques-et-Caïques",
            "TV" => "Tuvalu",
            "UG" => "Ouganda",
            "UA" => "Ukraine",
            "AE" => "Émirats Arabes Unis",
            "GB" => "Royaume-Uni",
            "US" => "États-Unis d'Amérique",
            "UM" => "Îles mineures éloignées des États-Unis",
            "UY" => "Uruguay",
            "UZ" => "Ouzbékistan",
            "VU" => "Vanuatu",
            "VE" => "Venezuela",
            "VN" => "Vietnam",
            "VG" => "Îles vierges britanniques",
            "VI" => "Îles vierges américaines",
            "WF" => "Wallis-et-Futuna",
            "EH" => "Sahara occidental",
            "YE" => "Yémen",
            "ZM" => "Zambie",
            "ZW" => "Zimbabwe",
            "AX" => "Åland",
            "BQ" => "Bonaire, Saint-Eustache et Saba",
            "CW" => "Curaçao",
            "GG" => "Guernesey",
            "IM" => "Île de Man",
            "JE" => "Jersey",
            "ME" => "Monténégro",
            "BL" => "Saint-Barthélemy",
            "MF" => "Saint-Martin (partie française)",
            "RS" => "Serbie",
            "SX" => "Saint-Martin (partie néerlandaise)",
            "SS" => "Soudan du Sud",
            "XK" => "Kosovo"
        ],
        'it' => [
            "AD" => "Andorra",
            "AE" => "Emirati Arabi Uniti",
            "AF" => "Afghanistan",
            "AG" => "Antigua e Barbuda",
            "AI" => "Anguilla",
            "AL" => "Albania",
            "AM" => "Armenia",
            "AO" => "Angola",
            "AQ" => "Antartide",
            "AR" => "Argentina",
            "AS" => "Samoa Americane",
            "AT" => "Austria",
            "AU" => "Australia",
            "AW" => "Aruba",
            "AX" => "Isole Åland",
            "AZ" => "Azerbaigian",
            "BA" => "Bosnia ed Erzegovina",
            "BB" => "Barbados",
            "BD" => "Bangladesh",
            "BE" => "Belgio",
            "BF" => "Burkina Faso",
            "BG" => "Bulgaria",
            "BH" => "Bahrain",
            "BI" => "Burundi",
            "BJ" => "Benin",
            "BL" => "Saint-Barthélemy",
            "BM" => "Bermuda",
            "BN" => "Brunei",
            "BO" => "Bolivia",
            "BQ" => "Isole BES",
            "BR" => "Brasile",
            "BS" => "Bahamas",
            "BT" => "Bhutan",
            "BV" => "Isola Bouvet",
            "BW" => "Botswana",
            "BY" => "Bielorussia",
            "BZ" => "Belize",
            "CA" => "Canada",
            "CC" => "Isole Cocos e Keeling",
            "CD" => "Repubblica Democratica del Congo",
            "CF" => "Repubblica Centrafricana",
            "CG" => "Repubblica del Congo",
            "CH" => "Svizzera",
            "CI" => "Costa d'Avorio",
            "CK" => "Isole Cook",
            "CL" => "Cile",
            "CM" => "Camerun",
            "CN" => "Cina",
            "CO" => "Colombia",
            "CR" => "Costa Rica",
            "CU" => "Cuba",
            "CV" => "Capo Verde",
            "CW" => "Curaçao",
            "CX" => "Isola del Natale",
            "CY" => "Cipro",
            "CZ" => "Repubblica Ceca",
            "DE" => "Germania",
            "DJ" => "Gibuti",
            "DK" => "Danimarca",
            "DM" => "Dominica",
            "DO" => "Repubblica Dominicana",
            "DZ" => "Algeria",
            "EC" => "Ecuador",
            "EE" => "Estonia",
            "EG" => "Egitto",
            "EH" => "Sahara Occidentale",
            "ER" => "Eritrea",
            "ES" => "Spagna",
            "ET" => "Etiopia",
            "FI" => "Finlandia",
            "FJ" => "Figi",
            "FK" => "Isole Falkland",
            "FM" => "Stati Federati di Micronesia",
            "FO" => "Isole Fær Øer",
            "FR" => "Francia",
            "GA" => "Gabon",
            "GB" => "Regno Unito",
            "GD" => "Grenada",
            "GE" => "Georgia",
            "GF" => "Guyana Francese",
            "GG" => "Guernsey",
            "GH" => "Ghana",
            "GI" => "Gibilterra",
            "GL" => "Groenlandia",
            "GM" => "Gambia",
            "GN" => "Guinea",
            "GP" => "Guadalupa",
            "GQ" => "Guinea Equatoriale",
            "GR" => "Grecia",
            "GS" => "Georgia del Sud e isole Sandwich meridionali",
            "GT" => "Guatemala",
            "GU" => "Guam",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HK" => "Hong Kong",
            "HM" => "Isole Heard e McDonald",
            "HN" => "Honduras",
            "HR" => "Croazia",
            "HT" => "Haiti",
            "HU" => "Ungheria",
            "ID" => "Indonesia",
            "IE" => "Irlanda",
            "IL" => "Israele",
            "IM" => "Isola di Man",
            "IN" => "India",
            "IO" => "Territori Britannici dell'Oceano Indiano",
            "IQ" => "Iraq",
            "IR" => "Iran",
            "IS" => "Islanda",
            "IT" => "Italia",
            "JE" => "Jersey",
            "JM" => "Giamaica",
            "JO" => "Giordania",
            "JP" => "Giappone",
            "KE" => "Kenya",
            "KG" => "Kirghizistan",
            "KH" => "Cambogia",
            "KI" => "Kiribati",
            "KM" => "Comore",
            "KN" => "Saint Kitts e Nevis",
            "KP" => "Corea del Nord",
            "KR" => "Corea del Sud",
            "KW" => "Kuwait",
            "KY" => "Isole Cayman",
            "KZ" => "Kazakistan",
            "LA" => "Laos",
            "LB" => "Libano",
            "LC" => "Santa Lucia",
            "LI" => "Liechtenstein",
            "LK" => "Sri Lanka",
            "LR" => "Liberia",
            "LS" => "Lesotho",
            "LT" => "Lituania",
            "LU" => "Lussemburgo",
            "LV" => "Lettonia",
            "LY" => "Libia",
            "MA" => "Marocco",
            "MC" => "Monaco",
            "MD" => "Moldavia",
            "ME" => "Montenegro",
            "MF" => "Saint-Martin",
            "MG" => "Madagascar",
            "MH" => "Isole Marshall",
            "MK" => "Macedonia del Nord",
            "ML" => "Mali",
            "MM" => "Birmania  Myanmar",
            "MN" => "Mongolia",
            "MO" => "Macao",
            "MP" => "Isole Marianne Settentrionali",
            "MQ" => "Martinica",
            "MR" => "Mauritania",
            "MS" => "Montserrat",
            "MT" => "Malta",
            "MU" => "Mauritius",
            "MV" => "Maldive",
            "MW" => "Malawi",
            "MX" => "Messico",
            "MY" => "Malesia",
            "MZ" => "Mozambico",
            "NA" => "Namibia",
            "NC" => "Nuova Caledonia",
            "NE" => "Niger",
            "NF" => "Isola Norfolk",
            "NG" => "Nigeria",
            "NI" => "Nicaragua",
            "NL" => "Paesi Bassi",
            "NO" => "Norvegia",
            "NP" => "Nepal",
            "NR" => "Nauru",
            "NU" => "Niue",
            "NZ" => "Nuova Zelanda",
            "OM" => "Oman",
            "PA" => "Panamá",
            "PE" => "Perù",
            "PF" => "Polinesia Francese",
            "PG" => "Papua Nuova Guinea",
            "PH" => "Filippine",
            "PK" => "Pakistan",
            "PL" => "Polonia",
            "PM" => "Saint Pierre e Miquelon",
            "PN" => "Isole Pitcairn",
            "PR" => "Porto Rico",
            "PS" => "Stato di Palestina",
            "PT" => "Portogallo",
            "PW" => "Palau",
            "PY" => "Paraguay",
            "QA" => "Qatar",
            "RE" => "Réunion",
            "RO" => "Romania",
            "RS" => "Serbia",
            "RU" => "Russia",
            "RW" => "Ruanda",
            "SA" => "Arabia Saudita",
            "SB" => "Isole Salomone",
            "SC" => "Seychelles",
            "SD" => "Sudan",
            "SE" => "Svezia",
            "SG" => "Singapore",
            "SH" => "Sant'Elena, Isola di Ascensione e Tristan da Cunha",
            "SI" => "Slovenia",
            "SJ" => "Svalbard e Jan Mayen",
            "SK" => "Slovacchia",
            "SL" => "Sierra Leone",
            "SM" => "San Marino",
            "SN" => "Senegal",
            "SO" => "Somalia",
            "SR" => "Suriname",
            "SS" => "Sudan del Sud",
            "ST" => "São Tomé e Príncipe",
            "SV" => "El Salvador",
            "SX" => "Sint Maarten",
            "SY" => "Siria",
            "SZ" => "Eswatini",
            "TC" => "Isole Turks e Caicos",
            "TD" => "Ciad",
            "TF" => "Territori Francesi del Sud",
            "TG" => "Togo",
            "TH" => "Thailandia",
            "TJ" => "Tagikistan",
            "TK" => "Tokelau",
            "TL" => "Timor Est",
            "TM" => "Turkmenistan",
            "TN" => "Tunisia",
            "TO" => "Tonga",
            "TR" => "Turchia",
            "TT" => "Trinidad e Tobago",
            "TV" => "Tuvalu",
            "TW" => ["Repubblica di Cina", "Taiwan"],
            "TZ" => "Tanzania",
            "UA" => "Ucraina",
            "UG" => "Uganda",
            "UM" => "Isole minori esterne degli Stati Uniti",
            "US" => "Stati Uniti d'America",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VA" => "Città del Vaticano",
            "VC" => "Saint Vincent e Grenadine",
            "VE" => "Venezuela",
            "VG" => "Isole Vergini Britanniche",
            "VI" => "Isole Vergini Americane",
            "VN" => "Vietnam",
            "VU" => "Vanuatu",
            "WF" => "Wallis e Futuna",
            "WS" => "Samoa",
            "YE" => "Yemen",
            "YT" => "Mayotte",
            "ZA" => "Sudafrica",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe",
            "XK" => "Kosovo"
        ]
    ];

    $countryCode = strtoupper($code);

    if (isset($countries[$local]) && isset($countries[$local][$code])) {
        return $countries[$local][$countryCode] ?? null;
    }

    return null;
}


function getNextPrefixId($modelName, $condition = null)
{

    $className = "\App\Models\\$modelName";

    if (!class_exists($className)) {
        throw new NotFoundHttpException("Model Not Found");
    }

    if (!defined("$className::PREFIX")) {
        throw  new Exception("PREFIX not found on model", 500);
    }

    $latest_prefix = $className::when($condition, fn ($q) => $condition($q))->max('prefix_id');

    // if ($modelName == 'OrganizationElement') {
    //     $latest_prefix = OrganizationElement::->orderBy('prefix_id', 'DESC')->first()?->prefix_id;
    // }

    $model_prefix = $className::PREFIX;

    if (!$latest_prefix) {
        return sprintf("$model_prefix%05d", 1);
    }

    $number = (int) str_replace($model_prefix, "", $latest_prefix) + 1;
    return sprintf("$model_prefix%05d", $number);
}

function getResourcePath()
{
    return base_path();
}





/**
     * Language Code order by user language
     *
     * @return void
     */
    function getLanguageNameByUser()
    {
        $language_code = auth()->user()->language->code;


        $languages =  Cache::rememberForever('all-languages-'.$language_code, function () {
            $languages_content = file_get_contents(base_path(sprintf('node_modules/@cospired/i18n-iso-languages/langs/%s.json', auth()->user()->language->code)));

            $languages = json_decode(($languages_content), TRUE);
            $languages = $languages['languages'];

            return $languages;
        });

        return $languages;
    }


    function getOrderByLanguageNameByUser($direction = 'asc'){
        $language_code = auth()->user()->language->code;


        $languages =  Cache::rememberForever('language-'.$direction.'-'.$language_code, function () use($direction) {
            $languages_content = file_get_contents(base_path(sprintf('node_modules/@cospired/i18n-iso-languages/langs/%s.json', auth()->user()->language->code)));

            $languages = json_decode(($languages_content), TRUE);
            $languages = $languages['languages'];


            if(strtolower($direction)  == 'asc') {
                asort($languages);
            }
            else {
                arsort($languages);
            }

            $count = 1;

            $query = 'CASE correspondence_language ';
            foreach($languages as $key => $value) {
                $query.= "WHEN '{$key}' THEN {$count} ";
                $count++;
            }
            $query .= 'END';
            return $query;
        });

        return $languages;
    }
